---
apiVersion: "v1"
kind: "List"
items:

  - apiVersion: v1
    kind: "Namespace"
    metadata:
      name: "mendix"
      labels:
        name: "mendix"
        
  - apiVersion: apps/v1beta1
    kind: "Deployment"
    metadata:
      name: mendixapp-deployment
      namespace: mendix
    spec:
      replicas: 1 # tells deployment to run 1 pod matching the template
      template: # create pods using pod definition in this template
        metadata:
          labels:
            app: "mendixappsample"
        spec:
          containers:
          - name: mendixapp
            image: 9golf/mendix:latest
            ports:
            - containerPort: 80
            env:
              - name: DATABASE_ENDPOINT
                value: "postgres://postgres:myPostgre@mypostgre.ctr6lvddgsuy.ap-southeast-1.rds.amazonaws.com:5432/mendix"
              - name: ADMIN_PASSWORD
                value: "Password1!"
                
  - apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "mendixapp"
      namespace: "mendix"
      labels:
        app: "mendixappsample"
    spec:
      type: "LoadBalancer"
      selector:
        app: "mendixappsample"
      ports:
      - port: 80

          
